# Generated by Django 5.1.2 on 2026-02-25 03:47

import django.utils.timezone
import gerenteApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('costo_compra', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_facturas',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('numero_factura', models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de factura')),
                ('fecha', models.DateField(default=gerenteApp.models.fecha_ayer, verbose_name='Fecha')),
                ('monto_total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='PrecioHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_costo_anterior', models.IntegerField()),
                ('precio_costo_nuevo', models.IntegerField()),
                ('precio_venta_anterior', models.IntegerField(blank=True, null=True)),
                ('precio_venta_nuevo', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'precios_historicos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='proveedor_id')),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('persona_contacto', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField(null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
    ]
