# Generated by Django 5.1.2 on 2024-12-04 23:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='proveedor_id')),
                ('nombre', models.CharField(max_length=100)),
                ('persona_contacto', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('direccion', models.TextField(null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
    ]
