# Generated by Django 6.0.4 on 2026-07-14 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0004_factura_id_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.BigIntegerField(verbose_name='Número de factura'),
        ),
    ]
