# Generated by Django 6.0.4 on 2026-07-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0005_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('direccion', models.TextField(blank=True, default='')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
            ],
            options={
                'db_table': 'store_config',
            },
        ),
    ]
