# Generated by Django 6.0.4 on 2026-07-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0006_store_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='timezone',
            field=models.CharField(blank=True, default='America/Santiago', max_length=100),
        ),
    ]
