# Generated by Django 6.0.4 on 2026-07-30 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0007_add_storeconfig_timezone'),
        ('vendedorApp', '0029_pedido_cancelado_estado_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='ubicacion_por_defecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedorApp.ubicacion'),
        ),
    ]
