# Generated by Django 6.0.4 on 2026-08-01 16:15

import gerenteApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0008_storeconfig_ubicacion_por_defecto'),
        ('vendedorApp', '0030_venta_documento_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(db_index=True, default=gerenteApp.models.fecha_ayer, verbose_name='Fecha'),
        ),
        migrations.AddIndex(
            model_name='detallefactura',
            index=models.Index(fields=['producto', 'factura'], name='detalle_fac_product_7de0fc_idx'),
        ),
    ]
