# Generated by Django 6.0.4 on 2026-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0009_alter_factura_fecha_and_more'),
        ('vendedorApp', '0033_devolucion_pedido_return'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='preciohistorico',
            index=models.Index(fields=['producto', '-fecha'], name='precio_hist_prod_fecha_idx'),
        ),
    ]
