# Generated by Django 6.0.4 on 2026-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0010_preciohistorico_precio_hist_prod_fecha_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='currency_code',
            field=models.CharField(blank=True, default='CLP', max_length=3),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='default_shipping_cost',
            field=models.IntegerField(default=4500),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='locale',
            field=models.CharField(blank=True, default='es-CL', max_length=20),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='price_round_to',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='total_round_threshold',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='total_round_to',
            field=models.IntegerField(default=1000),
        ),
    ]
