# Generated by Django 6.0.4 on 2026-09-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0012_seed_storeconfig_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='document_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
