# Generated by Django 6.0.4 on 2026-09-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0014_habilitar_order_pricing_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='rut',
            new_name='tax_id',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID tributario'),
        ),
        migrations.AddField(
            model_name='storeconfig',
            name='product_search_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]