# nginx.conf

upstream django_app {
    # 'app' es el nombre del servicio en docker-compose.yml
    # '8000' es el puerto que Gunicorn expone DENTRO de la red de Docker
    server app:8000;
}

server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Servir archivos estáticos
    location /static/ {
        # Esta es la ruta que Nginx ve DENTRO de su contenedor
        alias /var/www/static/; 
    }

    # Servir archivos media
    location /media/ {
        alias /var/www/media/;
    }

    location /api/ {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin/ {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /health/ {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Servir frontend (dashboard/login)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
