# Generated by Django 5.1.2 on 2026-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0002_add_marca_to_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='oem',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
