# Generated by Django 6.0.4 on 2026-05-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0007_remove_producto_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
