# Generated by Django 6.0.4 on 2026-07-15 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0008_ubicacion_nombre_unique_marca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_anulacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacion', to='vendedorApp.venta')),
            ],
            options={
                'db_table': 'anulaciones',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='vendedorApp.venta')),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('reponer_stock', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendedorApp.producto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='vendedorApp.devolucion')),
            ],
            options={
                'db_table': 'detalle_devoluciones',
            },
        ),
    ]
