# Generated by Django 6.0.4 on 2026-07-21 14:21

import django.db.models.deletion
import vendedorApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0009_anulacion_devolucion_detalledevolucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.IntegerField()),
                ('cantidad_nueva', models.IntegerField()),
                ('motivo', models.TextField()),
                ('fecha_ajuste', models.DateField(default=vendedorApp.models.fecha_hoy)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_stock', to='vendedorApp.producto')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedorApp.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ajustes_stock',
                'ordering': ['-fecha_ajuste', '-id'],
            },
        ),
    ]
