# Generated by Django 6.0.4 on 2026-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0010_ajuste_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_porcentaje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
