# Generated by Django 6.0.4 on 2026-07-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0011_venta_descuento_porcentaje_venta_monto_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ignorar_stock_permanente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='recordar_stock_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
