# Generated by Django 6.0.4 on 2026-07-23 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0005_alter_factura_numero_factura'),
        ('vendedorApp', '0012_producto_ignorar_stock_permanente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('VE', 'Venta'), ('CO', 'Cotizacion'), ('PE', 'Pedido')], default='VE', max_length=2),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=50)),
                ('monto_subtotal', models.IntegerField()),
                ('monto_total', models.IntegerField()),
                ('costo_envio', models.IntegerField(default=4500)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta')], default='EF', max_length=2)),
                ('facturado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido', to='vendedorApp.venta')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=50)),
                ('oem', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('precio_costo', models.IntegerField()),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_final', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='vendedorApp.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedorApp.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenteApp.proveedor')),
            ],
            options={
                'db_table': 'pedido_detalles',
            },
        ),
    ]
