# Generated by Django 6.0.4 on 2026-07-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0013_alter_venta_tipo_documento_pedido_pedidodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='facturado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PR', 'Pendiente por retirar'), ('RE', 'Retirado')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_documento',
            field=models.CharField(choices=[('SB', 'Sin boletear'), ('BO', 'Boleteado'), ('FA', 'Facturado')], default='SB', max_length=2),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
