# Generated by Django 6.0.4 on 2026-07-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0016_ignorar_stock_permanente_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='stellantis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='sumar_envio',
            field=models.BooleanField(default=True),
        ),
    ]
