# Generated by Django 6.0.4 on 2026-07-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0017_pedidodetalle_stellantis_pedidodetalle_sumar_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oem_alternativo',
            field=models.TextField(blank=True, null=True, verbose_name='OEM alternativos'),
        ),
    ]
