# Generated by Django 6.0.4 on 2026-07-24 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0018_producto_oem_alternativo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproductoubicacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ajustestock',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedorApp.ubicacion'),
        ),
        migrations.AlterField(
            model_name='stockproductoubicacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedorApp.ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='stockproductoubicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('ubicacion__isnull', False)), fields=('producto', 'ubicacion'), name='unique_producto_ubicacion'),
        ),
    ]
