# Generated by Django 6.0.4 on 2026-07-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0019_alter_stockproductoubicacion_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockproductoubicacion',
            name='unique_producto_ubicacion',
        ),
        migrations.AlterUniqueTogether(
            name='stockproductoubicacion',
            unique_together={('producto', 'ubicacion')},
        ),
    ]
