# Generated by Django 6.0.4 on 2026-07-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0021_add_precio_descontado_and_monto_devuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='venta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_derivadas', to='vendedorApp.venta', verbose_name='Venta origen'),
        ),
    ]
