# Generated by Django 6.0.4 on 2026-07-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0022_venta_venta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del cliente'),
        ),
    ]
