# Generated by Django 6.0.4 on 2026-07-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0022_venta_venta_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_proveedor',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código proveedor'),
        ),
    ]
