# Generated by Django 6.0.4 on 2026-07-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0023_producto_codigo_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_cotizacion',
            field=models.BooleanField(default=False, verbose_name='Es cotización'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_derivados', to='vendedorApp.pedido', verbose_name='Pedido origen (cotización)'),
        ),
    ]
