# Generated by Django 6.0.4 on 2026-07-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0007_add_storeconfig_timezone'),
        ('vendedorApp', '0024_pedido_es_cotizacion_pedido_pedido_origen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoProveedorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedidos_proveedor_dia',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedorApp.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenteApp.proveedor')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendedorApp.pedidoproveedordia')),
            ],
            options={
                'db_table': 'items_pedido_proveedor',
                'unique_together': {('dia', 'producto')},
            },
        ),
    ]
