# Generated by Django 6.0.4 on 2026-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0025_pedidoproveedordia_itempedidoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedordia',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
