# Generated by Django 6.0.4 on 2026-07-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0026_pedidoproveedordia_finalizado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempedidoproveedor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itempedidoproveedor',
            name='codigo_proveedor_custom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='itempedidoproveedor',
            name='nombre_custom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='itempedidoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedorApp.producto'),
        ),
    ]
