# Generated by Django 6.0.4 on 2026-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0028_sync_cliente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PR', 'Pendiente por retirar'), ('RE', 'Retirado'), ('CA', 'Cancelado')], default='PR', max_length=2),
        ),
    ]
