# Generated by Django 6.0.4 on 2026-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0029_pedido_cancelado_estado_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='documento_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
