# Generated by Django 6.0.4 on 2026-08-01 16:15

import django.utils.timezone
import vendedorApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenteApp', '0009_alter_factura_fecha_and_more'),
        ('vendedorApp', '0030_venta_documento_html'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajustestock',
            name='fecha_ajuste',
            field=models.DateField(db_index=True, default=vendedorApp.models.fecha_hoy),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PR', 'Pendiente por retirar'), ('RE', 'Retirado'), ('CA', 'Cancelado')], db_index=True, default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_proveedor',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Código proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='oem',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('CO', 'Completada'), ('CA', 'Cancelada')], db_index=True, default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_documento',
            field=models.CharField(choices=[('VE', 'Venta'), ('CO', 'Cotizacion'), ('PE', 'Pedido')], db_index=True, default='VE', max_length=2),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['marca', 'nombre'], name='productos_marca_4fe699_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha_venta'], name='ventas_estado_537d75_idx'),
        ),
    ]
