# Generated by Django 6.0.4 on 2026-08-17 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0031_alter_ajustestock_fecha_ajuste_alter_pedido_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='documento',
            field=models.CharField(blank=True, choices=[('BO', 'Boleta'), ('FA', 'Factura'), ('OT', 'Otros')], db_index=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('total_vendido', models.IntegerField(default=0)),
                ('total_devoluciones', models.IntegerField(default=0)),
                ('total_anulaciones', models.IntegerField(default=0)),
                ('total_final', models.IntegerField(default=0)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('efectivo', models.IntegerField(default=0)),
                ('tarjeta', models.IntegerField(default=0)),
                ('transferencia', models.IntegerField(default=0)),
                ('cheque', models.IntegerField(default=0)),
                ('pago_sin_clasificar', models.IntegerField(default=0)),
                ('boleta', models.IntegerField(default=0)),
                ('factura', models.IntegerField(default=0)),
                ('otros', models.IntegerField(default=0)),
                ('doc_sin_clasificar', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cierres_caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta'), ('TR', 'Transferencia'), ('CH', 'Cheque')], db_index=True, max_length=2)),
                ('monto', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='vendedorApp.venta')),
            ],
            options={
                'db_table': 'pagos_ventas',
            },
        ),
    ]
