# Generated by Django 6.0.4 on 2026-08-18 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0032_venta_pagos_cierre_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledevolucion',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='pedido_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='vendedorApp.pedidodetalle'),
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalledevolucion',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vendedorApp.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PR', 'Pendiente por retirar'), ('RE', 'Retirado'), ('DE', 'Devuelto'), ('CA', 'Cancelado')], db_index=True, default='PR', max_length=2),
        ),
    ]
