# Generated by Django 6.0.4 on 2026-08-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0033_devolucion_pedido_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_ventas', to='vendedorApp.ubicacion'),
        ),
    ]
