# Generated by Django 6.0.4 on 2026-08-25 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0034_detalleventa_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_stock', to='vendedorApp.stockproductoubicacion')),
            ],
            options={
                'db_table': 'stock_historico',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['stock', 'fecha'], name='stock_hist_stock_fecha_idx')],
            },
        ),
    ]
