# Generated by Django 6.0.4 on 2026-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0035_stockhistorico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_documento',
            field=models.CharField(choices=[('SB', 'Sin boletear'), ('BO', 'Boleteado'), ('FA', 'Facturado'), ('OT', 'Otros')], default='SB', max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TJ', 'Tarjeta'), ('TR', 'Transferencia'), ('CH', 'Cheque')], default='EF', max_length=2),
        ),
    ]
