# Generated by Django 6.0.4 on 2026-09-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0036_alter_pedido_estado_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='deduccion_original',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
