# Generated by Django 6.0.4 on 2026-09-03 16:06

from django.db import migrations, models


def migrar_stellantis_a_cost_modifiers(apps, schema_editor):
    PedidoDetalle = apps.get_model("vendedorApp", "PedidoDetalle")
    for detalle in PedidoDetalle.objects.filter(stellantis=True):
        detalle.cost_modifiers = ["stellantis"]
        detalle.save(update_fields=["cost_modifiers"])


def desmigrar_cost_modifiers_a_stellantis(apps, schema_editor):
    PedidoDetalle = apps.get_model("vendedorApp", "PedidoDetalle")
    for detalle in PedidoDetalle.objects.filter(cost_modifiers__contains=["stellantis"]):
        detalle.stellantis = True
        detalle.save(update_fields=["stellantis"])


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0037_venta_deduccion_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='cost_modifiers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrar_stellantis_a_cost_modifiers, desmigrar_cost_modifiers_a_stellantis),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='stellantis',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='desglose',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='costo_envio',
            field=models.IntegerField(default=0),
        ),
    ]
