# Generated by Django 6.0.4 on 2026-09-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0038_remove_pedidodetalle_stellantis_cierrecaja_desglose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='idempotencia_key',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='Clave de idempotencia'),
        ),
    ]
