# Generated by Django 6.0.4 on 2026-09-04 14:14

import django.db.models.functions.comparison
from django.db import migrations, models


def dedupe_stock_ubicacion(apps, schema_editor):
    """Fusiona filas duplicadas de stock_producto_ubicacion (mismo producto/ubicación).

    En MariaDB un índice UNIQUE no trata NULL como un valor, por lo que podían
    existir varias filas con (producto, ubicacion=NULL) para "sin ubicación".
    Antes de crear el índice único sobre (producto, ubicacion_key) se suman las
    cantidades en la fila de menor id y se eliminan las restantes.
    """
    connection = schema_editor.connection
    with connection.cursor() as cur:
        cur.execute(
            """
            CREATE TEMPORARY TABLE _stock_keep AS
            SELECT producto_id, ubicacion_id, MIN(id) AS keep_id, SUM(cantidad) AS total
            FROM stock_producto_ubicacion
            GROUP BY producto_id, ubicacion_id
            HAVING COUNT(*) > 1
            """
        )
        cur.execute(
            """
            UPDATE stock_producto_ubicacion s
            JOIN _stock_keep k ON s.id = k.keep_id
            SET s.cantidad = k.total
            """
        )
        cur.execute(
            """
            UPDATE stock_historico h
            JOIN stock_producto_ubicacion s ON h.stock_id = s.id
            JOIN _stock_keep k
              ON s.producto_id = k.producto_id
             AND IFNULL(s.ubicacion_id, 0) = IFNULL(k.ubicacion_id, 0)
             AND s.id != k.keep_id
            SET h.stock_id = k.keep_id
            """
        )
        cur.execute(
            """
            DELETE s FROM stock_producto_ubicacion s
            JOIN _stock_keep k
              ON s.producto_id = k.producto_id
             AND IFNULL(s.ubicacion_id, 0) = IFNULL(k.ubicacion_id, 0)
            WHERE s.id != k.keep_id
            """
        )
        cur.execute("DROP TEMPORARY TABLE _stock_keep")


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0039_venta_idempotencia_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproductoubicacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockproductoubicacion',
            name='ubicacion_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('ubicacion_id'), models.Value(0)), output_field=models.IntegerField()),
        ),
        migrations.RunPython(dedupe_stock_ubicacion, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='stockproductoubicacion',
            unique_together={('producto', 'ubicacion_key')},
        ),
    ]