# Generated by Django 6.0.4 on 2026-09-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedorApp', '0040_alter_stockproductoubicacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
